---
title: "CUE_Davis_Soil_report"
output: 
  github_document:
  html_preview: True
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE
                      )
```


## Soil physical properties by site

<details>
  <summary>click to open</summary>

### Water infiltration measured in the field n=6

```{r , fig.height=8, fig.width=8, results='hide', out.width="100%"}
tar_read(Soil_infiltration)$gg_infiltration

```

### Bulk density of soil n=6
```{r , fig.height=8, fig.width=8, results='hide', out.width="100%"}
tar_read(Soil_infiltration)$gg_Bulk

```

### Proportion of each aggregate size by mass n=9

```{r , fig.height=8, fig.width=8, results='hide', out.width="100%"}
tar_read(Soil_Aggregate_proportion)

```

### WHC in organic and conventional soils. And by aggregate size. n=4

```{r , fig.height=8, fig.width=8, results='hide', out.width="100%"}
tar_read(Soil_Bulk2)

```

</details>


## Session Info 

<details>
  <summary> Session Info </summary>

Date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>